---
# Personal MacBook
all:
  hosts:
    localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: auto_silent
    home: "{{ ansible_facts['user_dir'] }}"
    dirs:
      home: "{{home}}"
      code: "{{home}}/code"
      bin: "{{home}}/.local/bin"
    # Machine-specific settings
    is_work_machine: false
    emacs_enabled: true
    hammerspoon_enabled: false
    aerospace_enabled: false
