---
# This task file is responsible for setting up Alacritty on my machine

- name: Install Alacritty
  homebrew_cask:
    name: alacritty
    state: present
    update_homebrew: no
  when: ansible_facts['os_family'] == "Darwin"

- name: alacritty homebrew dependencies
  homebrew:
    name:
      - ripgrep
      - lazygit
    update_homebrew: no
  when: ansible_facts['os_family'] == "Darwin"

- name: Make alacritty config directory
  file:
    path: "{{home}}/.config/alacritty"
    state: directory
